#!/bin/bash

# This fantastic piece of engineering is because I can't figure out how to do the equivalent in Browserify
# without ending up with a 500k pile of goop that doesn't function.   Pull requests welcome.

mkdir -p ../browser 

cat ../node_modules/browser-request/dist/browser/request.js > ../browser/nitrogen.js
cat ../node_modules/faye/browser/faye-browser.js >> ../browser/nitrogen.js

cat ../lib/authRequest.js | sed '/require(/d' | sed '/module.export/d' >> ../browser/nitrogen.js
cat ../lib/principal.js   | sed '/require(/d' | sed '/module.export/d' >> ../browser/nitrogen.js
cat ../lib/message.js     | sed '/require(/d' | sed '/module.export/d' >> ../browser/nitrogen.js
cat ../lib/heartbeat.js   | sed '/require(/d' | sed '/module.export/d' >> ../browser/nitrogen.js
cat ../lib/eventLog.js    | sed '/require(/d' | sed '/module.export/d' >> ../browser/nitrogen.js
cat ../lib/blob.js        | sed '/require(/d' | sed '/module.export/d' >> ../browser/nitrogen.js
cat ../lib/session.js     | sed '/require(/d' | sed '/module.export/d' >> ../browser/nitrogen.js
cat ../lib/service.js     | sed '/require(/d' | sed '/module.export/d' >> ../browser/nitrogen.js
cat ../lib/device.js      | sed '/require(/d' | sed '/module.export/d' >> ../browser/nitrogen.js
cat ../lib/html5Store.js  | sed '/require(/d' | sed '/module.export/d' >> ../browser/nitrogen.js
cat ../lib/user.js        | sed '/require(/d' | sed '/module.export/d' >> ../browser/nitrogen.js

cat module.js >> ../browser/nitrogen.js

uglifyjs ../browser/nitrogen.js -o ../browser/nitrogen-min.js
