#!/bin/bash

# This fantastic piece of engineering is because I can't figure out how to do the equivalent in Browserify
# without ending up with a 500k pile of goop that doesn't function.   Pull requests welcome.

cat ../node_modules/browser-request/dist/browser/request.js > ../browser/magenta.js
cat ../node_modules/faye/browser/faye-browser.js >> ../browser/magenta.js

cat ../magenta/authRequest.js | sed '/require(/d' | sed '/module.export/d' >> ../browser/magenta.js
cat ../magenta/principal.js   | sed '/require(/d' | sed '/module.export/d' >> ../browser/magenta.js
cat ../magenta/message.js     | sed '/require(/d' | sed '/module.export/d' >> ../browser/magenta.js
cat ../magenta/heartbeat.js   | sed '/require(/d' | sed '/module.export/d' >> ../browser/magenta.js
cat ../magenta/eventLog.js    | sed '/require(/d' | sed '/module.export/d' >> ../browser/magenta.js
cat ../magenta/blob.js        | sed '/require(/d' | sed '/module.export/d' >> ../browser/magenta.js
cat ../magenta/session.js     | sed '/require(/d' | sed '/module.export/d' >> ../browser/magenta.js
cat ../magenta/service.js     | sed '/require(/d' | sed '/module.export/d' >> ../browser/magenta.js
cat ../magenta/device.js      | sed '/require(/d' | sed '/module.export/d' >> ../browser/magenta.js
cat ../magenta/html5Store.js  | sed '/require(/d' | sed '/module.export/d' >> ../browser/magenta.js
cat ../magenta/user.js        | sed '/require(/d' | sed '/module.export/d' >> ../browser/magenta.js

cat module.js >> ../browser/magenta.js

uglifyjs ../browser/magenta.js -o ../browser/magenta-min.js
